
package Diseño;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdk.nashorn.api.scripting.JSObject;
import objetosfinal.AdministradorPerfil;
import org.json.simple.JSONObject;


public class Main extends javax.swing.JFrame {

        
    public Main() {
        initComponents();
        Color unicen = new Color(35, 71, 114);
        Color fondo = new Color(236, 232, 214);
        Color botones = new Color(35,71,114);
        
        this.getContentPane().setBackground(fondo);
        jPanel1.setBackground(unicen);
        procesarEncuestas.setBackground(botones);
        generarGrupos.setBackground(botones);
        datosGrupales.setBackground(botones);
        
        setLocationRelativeTo(null);
        setResizable(false); //no permite que se agrande la ventana
        setTitle("Formacion de Grupos");//agrega nombre a la ventana // VER BIEN EL NOMBRE
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        procesarEncuestas = new javax.swing.JButton();
        generarGrupos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datosGrupales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        procesarEncuestas.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        procesarEncuestas.setForeground(new java.awt.Color(255, 255, 255));
        procesarEncuestas.setText("Procesar Encuestas");
        procesarEncuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarEncuestasActionPerformed(evt);
            }
        });

        generarGrupos.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        generarGrupos.setForeground(new java.awt.Color(255, 255, 255));
        generarGrupos.setText("Generar grupos");
        generarGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarGruposActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo exactas.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formacion de Grupos    ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        datosGrupales.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        datosGrupales.setForeground(new java.awt.Color(255, 255, 255));
        datosGrupales.setText("Ver Datos Grupales");
        datosGrupales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosGrupalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datosGrupales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(procesarEncuestas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generarGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(procesarEncuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generarGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosGrupales, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {datosGrupales, generarGrupos});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void procesarEncuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarEncuestasActionPerformed
       //Se cambia la vista a VistaProcesadorEncuesta
        VistaProcesadorEncuesta obj;
        try {
            obj = new VistaProcesadorEncuesta();
            obj.setVisible(true); //SE NOS HACE VISIBLE LA PANTALLA
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_procesarEncuestasActionPerformed

    private void generarGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarGruposActionPerformed
        //Se cambia lavista a VistaGEneracionGrupo
        VistaGeneracionGrupo obj = new VistaGeneracionGrupo();
        obj.setVisible(true); //SE NOS HACE VISIBLE LA PANTALLA
        dispose();
    }//GEN-LAST:event_generarGruposActionPerformed

    private void datosGrupalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosGrupalesActionPerformed
    try{
        // Se cambia la vista a VistaMostrarDatos
        VistaMostrarDatos obj = new VistaMostrarDatos();
        obj.setVisible(true);
        dispose();
    }
    catch(Exception exc){
        exc.printStackTrace();
         JOptionPane.showMessageDialog(null, "ERROR" , "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_datosGrupalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datosGrupales;
    private javax.swing.JButton generarGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton procesarEncuestas;
    // End of variables declaration//GEN-END:variables
   
   

    
}
