/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import objetosfinal.AdministradorPerfil;
import org.json.simple.JSONObject;

/**
 *
 * @author eugem
 */
public class VistaMostrarDatos extends javax.swing.JFrame {

    private DefaultListModel defaultLista1;
    private AdministradorPerfil admPerfil;
    
    public VistaMostrarDatos() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false); //no permite que se agrande la ventana
        setTitle("Datos de Grupos");
        
        Color unicen = new Color(35, 71, 114);
        Color fondo = new Color(236, 232, 214);
        Color botones = new Color(35, 71,114);
        this.getContentPane().setBackground(fondo);
        jPanel1.setBackground(unicen);
        verDatos.setBackground(botones);
                
        defaultLista1= new DefaultListModel();
        admPerfil= new AdministradorPerfil();
        cargarLista();
    }
    
    private void cargarLista()
    {
        File fileFolder = new File("./PerfilesGrupales");
        File[] ficheros = fileFolder.listFiles();
        
        if (ficheros.length == 0){
            JOptionPane.showMessageDialog(null, "No se posee grupos por el momento", "Error", JOptionPane.ERROR_MESSAGE);
            Main obj = new Main();
            obj.setVisible(true); //SE NOS HACE VISIBLE LA PANTALLA
            dispose();
        }
        for (int x = 0; x < ficheros.length; x++) {
            defaultLista1.addElement(ficheros[x].getName());
        }
        jList1.setModel(defaultLista1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        verDatos = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        verDatos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        verDatos.setForeground(new java.awt.Color(255, 255, 255));
        verDatos.setText("Ver Datos");
        verDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDatosActionPerformed(evt);
            }
        });

        menuPrincipal.setText("Menu Principal");
        menuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo exactas.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Datos de Grupos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(verDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuPrincipal)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDatosActionPerformed
    try{
        String datos="";
        String nombre="";
        ArrayList<String> grupos = new ArrayList();
        JSONObject encuesta = new JSONObject();
        JSONObject integrantes = new JSONObject();
        JSONObject conformidad = new JSONObject();
        
        if (jList1.isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionarse un grupo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        nombre= (String) defaultLista1.getElementAt(jList1.getSelectedIndex());
        encuesta= admPerfil.getEncuestaGrupal(nombre, "feedBackSymlog");
        integrantes= admPerfil.getEncuestaGrupal(nombre, "integrantes");
        conformidad = admPerfil.getEncuestaGrupal(nombre, "conformidad");
        
        datos = datos + "Grupo " + nombre +": " +"\n";
            
        //Se acomodan los Integrantes
        datos = datos + "Integrantes: "  + "\n";
        datos = datos +  integrantes.get("integrantes");
        datos += "\n";
            
        //Se acomodan datos Symlog
        datos = datos + "Symlog Grupal: " + "\n";
        Set<String> setSymlog = encuesta.keySet();
        for (String s: setSymlog)
        {
            if((!s.startsWith("lista"))&&(!s.startsWith("Test")))
                datos = datos + s +  ": " + encuesta.get(s) + " - ";
        }
        datos += "\n";
            
        //Se acomodan las preguntas de conformidad con sus promedios
        Set<String> set = conformidad.keySet();
        for (String s : set)
        {
            if(!s.startsWith("lista"))
            {
                datos = datos + s +": "+  conformidad.get(s) + "\n";
            }
        }
        datos= datos + "\n";
        JOptionPane.showMessageDialog(null, datos);
    }
    catch(Exception exc){
        exc.printStackTrace();
         JOptionPane.showMessageDialog(null, "error en el sistema: no se pueden mostrar datos" , "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_verDatosActionPerformed

    private void menuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalActionPerformed
        Main obj = new Main();
        obj.setVisible(true); //SE NOS HACE VISIBLE LA PANTALLA
        dispose();
    }//GEN-LAST:event_menuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMostrarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menuPrincipal;
    private javax.swing.JButton verDatos;
    // End of variables declaration//GEN-END:variables
}
