/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import objetosfinal.AdministradorPerfil;
import objetosfinal.LectorEncuesta;
import objetosfinal.ProcesadorBelbin;
import objetosfinal.ProcesadorEncuesta;
import objetosfinal.ProcesadorFeedbackFinal;
import objetosfinal.ProcesadorFeedbackIndividual;
import objetosfinal.ProcesadorManejoConflictos;
import objetosfinal.ProcesadorSymlog;
import objetosfinal.ProcesadorTestFelder;
import org.json.simple.JSONObject;

public class VistaProcesadorEncuesta extends javax.swing.JFrame {
    String ultimaRuta;
    String rutaExcel;
    String procesadorActual;
    ProcesadorEncuesta procesador;
    FileReader hashSymlog;
    ProcesadorEncuesta procesadorSymlog;
    ProcesadorEncuesta procesadorConflictos;
    ProcesadorEncuesta procesadorBelbin;
    ProcesadorEncuesta procesadorFelder;
    ProcesadorEncuesta procesadorFeedbackInd;
    ProcesadorEncuesta procesadorFeedbackFinal;
    LectorEncuesta lector;
    ButtonGroup eleccion = new ButtonGroup();
    boolean seleccionEncuesta;
    boolean seleccionTipoEncuesta;

   
    public VistaProcesadorEncuesta() throws IOException {
        initComponents();

        Color unicen = new Color(35, 71, 114);
        Color fondo = new Color(236, 232, 214);
        Color panels = new Color(241, 239, 226);
        Color botones = new Color(35, 71,114);
        
        this.getContentPane().setBackground(fondo);
        jPanel1.setBackground(panels);
        jPanel2.setBackground(panels);
        jPanel3.setBackground(unicen);
        jButton1.setBackground(botones);
        
        setLocationRelativeTo(null);
        setResizable(false); //no permite que se agrande la ventana
        setTitle("Procesador de Encuestas");//agrega nombre a la ventana

        File datosConflictos = new File("matrizConflictos.txt");
        procesadorConflictos = new ProcesadorManejoConflictos(datosConflictos);

        FileReader datoSymlog = new FileReader("symlog.txt");
        procesadorSymlog = new ProcesadorSymlog(datoSymlog);

        procesadorFelder = new ProcesadorTestFelder();
        procesadorBelbin = new ProcesadorBelbin();
        procesadorFeedbackInd = new ProcesadorFeedbackIndividual();
        procesadorFeedbackFinal = new ProcesadorFeedbackFinal();

        lector = new LectorEncuesta();
        eleccion.add(chBelbin);
        eleccion.add(chConflictos);
        eleccion.add(chSymlog);
        eleccion.add(chFelder);
        eleccion.add(feedbackInd);
        eleccion.add(feedbackFinal);
        seleccionEncuesta = false;
        seleccionTipoEncuesta = false;
        this.deshabilitar();
        ultimaRuta = "./";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The co ntent of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Seleccionar = new javax.swing.JButton();
        ruta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        chBelbin = new javax.swing.JCheckBox();
        chConflictos = new javax.swing.JCheckBox();
        chSymlog = new javax.swing.JCheckBox();
        chFelder = new javax.swing.JCheckBox();
        feedbackInd = new javax.swing.JCheckBox();
        feedbackFinal = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setText("Menu Principal");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        Seleccionar.setText("Seleccionar Encuesta");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });

        ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Seleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Encuesta"));

        chBelbin.setText("Test Belbin");
        chBelbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBelbinActionPerformed(evt);
            }
        });

        chConflictos.setText("Manejo de Conflictos");
        chConflictos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chConflictosActionPerformed(evt);
            }
        });

        chSymlog.setText("Symlog");
        chSymlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSymlogActionPerformed(evt);
            }
        });

        chFelder.setText("Test Felder");
        chFelder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chFelderActionPerformed(evt);
            }
        });

        feedbackInd.setText("Feedback Individual");
        feedbackInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackIndActionPerformed(evt);
            }
        });

        feedbackFinal.setText("Feedback Final");
        feedbackFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chBelbin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chConflictos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chSymlog, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chFelder, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedbackInd, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedbackFinal)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(chBelbin)
                    .addComponent(chConflictos)
                    .addComponent(chSymlog)
                    .addComponent(chFelder)
                    .addComponent(feedbackInd)
                    .addComponent(feedbackFinal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Procesar");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo exactas.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROCESADOR DE ENCUESTA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Menu))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Menu))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        //Se cambia a la vista Main
        Main obj = new Main();
        obj.setVisible(true); //SE NOS HACE VISIBLE LA PANTALLA
        dispose();
        
    }//GEN-LAST:event_MenuActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
       //Se selecciona el archivo a utilizar
        JFileChooser chooser = new JFileChooser(ultimaRuta); // PERMITO LA SELECCION DE UN UNICO ARCHIVO
        
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY); // solo seleccionar achivos
        chooser.setMultiSelectionEnabled(false);//para que no se puedan seleccionar multiples archivos

        FileFilter filtro = new FileNameExtensionFilter("Tipo de archivo", "xls"); //FILTRO PARA QUE APAREZCAN SOLO ARCHIVOS CON EXTENSION XLS
        chooser.setFileFilter(filtro);

        int seleccion = chooser.showOpenDialog(null); //AGREGO RUTA DE ARCHIVO
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            ruta.setText(chooser.getSelectedFile().getAbsolutePath());
            rutaExcel = chooser.getSelectedFile().getAbsolutePath();
            ultimaRuta = rutaExcel;
        }
        seleccionEncuesta = true;
        if ((seleccionEncuesta) && (seleccionTipoEncuesta)) {
            habilitar();
        }
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void chBelbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBelbinActionPerformed
       //Se selecciona trabajar por belbin
        procesadorActual = "Belbin";
        procesador = procesadorBelbin;
        seleccionTipoEncuesta = true;
        if ((seleccionTipoEncuesta) && (seleccionTipoEncuesta)) {
            habilitar();
        }
    }//GEN-LAST:event_chBelbinActionPerformed

    private void chConflictosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chConflictosActionPerformed
        //Se selecciona trabajar por killman
        procesadorActual = "Manejo de Conflictos";
        procesador = procesadorConflictos;
        seleccionTipoEncuesta = true;
        if ((seleccionEncuesta) && (seleccionTipoEncuesta)) {
            habilitar();
        }
    }//GEN-LAST:event_chConflictosActionPerformed

    private void chSymlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSymlogActionPerformed
        //Se selecciona trabajar por Symlog
        procesadorActual = "Symlog";
        procesador = procesadorSymlog;
        seleccionTipoEncuesta = true;
        if ((seleccionEncuesta) && (seleccionTipoEncuesta)) {
            habilitar();
        }
    }//GEN-LAST:event_chSymlogActionPerformed

    private void chFelderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chFelderActionPerformed
        //Se selecciona trabajar por felder
        procesadorActual = "Felder";
        procesador = procesadorFelder;
        seleccionTipoEncuesta = true;
        if ((seleccionEncuesta) && (seleccionTipoEncuesta)) {
            habilitar();
        }
    }//GEN-LAST:event_chFelderActionPerformed

    public void habilitar() {
        //habilita el boton para procesar la encuesta
        jButton1.setEnabled(true);
    }

    public void deshabilitar() {
        //deshabilita el boton para procesar la encuesta
        jButton1.setEnabled(false);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
        //SE obtiene el JSONObject del test pedido, se procesa y se almacena en la carpeta de los perfiles
        AdministradorPerfil ap = new AdministradorPerfil();
        List<JSONObject> objetos = lector.readExcelFile(new File(rutaExcel));
        JSONObject resultado = new JSONObject();
        for(JSONObject jo:objetos){
		resultado = procesador.getResultado(jo);
		if (resultado != null){
			String nombre = (String) jo.get("Nombre");
			if (jo.get("Apellido") != null)
				nombre+=" "+jo.get("Apellido");
                    try {
                        ap.agregarEncuesta(nombre,resultado,procesador.getNombre() );
                    } catch (IOException ex) {
                        Logger.getLogger(VistaProcesadorEncuesta.class.getName()).log(Level.SEVERE, null, ex);
                    }
		}
        }
         JOptionPane.showMessageDialog(null, "El test fue procesado con Exito", "Mensaje", JOptionPane.UNDEFINED_CONDITION);
    }
    catch(Exception exc){
        exc.printStackTrace();
         JOptionPane.showMessageDialog(null, "ERROR" , "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaActionPerformed

    private void feedbackIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackIndActionPerformed
        //Se selecciona trabajar por feedback
        procesadorActual = "feedback";
        procesador = procesadorFeedbackInd;
        seleccionTipoEncuesta = true;
        if ((seleccionEncuesta) && (seleccionTipoEncuesta)) {
            habilitar();
        }
    }//GEN-LAST:event_feedbackIndActionPerformed

    private void feedbackFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackFinalActionPerformed
        procesadorActual = "feedbackFinal";
        procesador = procesadorFeedbackFinal;
        seleccionTipoEncuesta = true;
        if ((seleccionEncuesta) && (seleccionTipoEncuesta)) {
            habilitar();
        }
    }//GEN-LAST:event_feedbackFinalActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProcesadorEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProcesadorEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProcesadorEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProcesadorEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaProcesadorEncuesta().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VistaProcesadorEncuesta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JCheckBox chBelbin;
    private javax.swing.JCheckBox chConflictos;
    private javax.swing.JCheckBox chFelder;
    private javax.swing.JCheckBox chSymlog;
    private javax.swing.JCheckBox feedbackFinal;
    private javax.swing.JCheckBox feedbackInd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField ruta;
    // End of variables declaration//GEN-END:variables
}
